language: node_js
node_js:
  - node

script: webpack

notifications:
  - email: false

ddons:
  ssh_known_hosts: ben-willis.co.uk

before_deploy:
  - openssl aes-256-cbc -K $encrypted_808570c71b9f_key -iv $encrypted_808570c71b9f_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

  - cp -r index.html build.js manifest.json icons build

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build ben@ben-willis.co.uk:/home/ben/wc2018
  on:
    branch: master